# Generated by Django 5.1.2 on 2024-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendador',
            name='ine_image',
            field=models.ImageField(blank=True, null=True, upload_to='ine_images', verbose_name='INE'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='ine_image',
            field=models.ImageField(blank=True, null=True, upload_to='ine_images', verbose_name='INE'),
        ),
        migrations.AlterField(
            model_name='arrendador',
            name='is_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arrendatario',
            name='is_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
