# Generated by Django 5.1.2 on 2024-10-28 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_arrendador_ine_image_arrendatario_ine_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrendador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='arrendatario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrendatario', to=settings.AUTH_USER_MODEL),
        ),
    ]
