# Generated by Django 5.1.2 on 2024-10-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_arrendador_usuario_alter_arrendatario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendador',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Foto de perfil'),
        ),
    ]
