# Generated by Django 4.2.16 on 2024-10-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_arrendador_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendador',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='Foto de Perfil'),
        ),
    ]
