# Generated by Django 5.1.2 on 2024-11-14 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_tool_mensaje_rechazo'),
        ('users', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.tool'),
        ),
    ]
