# Generated by Django 4.2.16 on 2024-10-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_arrendador_profile_picture_and_more'),
        ('tools', '0003_delete_renta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas', models.PositiveIntegerField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada')], max_length=20)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendatario')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
        ),
    ]
