# Generated by Django 4.2.16 on 2024-11-04 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_arrendador_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0006_alter_tool_estado'),
        ('rentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendador')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendatario')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
                ('renta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentas.renta')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('enviado', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='rentas.chat')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
