# Generated by Django 4.2.16 on 2024-11-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_alter_tool_estado'),
        ('users', '0006_arrendador_profile_picture_and_more'),
        ('rentas', '0002_chat_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendatario')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='tools.tool')),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentas.renta'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendador')),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='rentas.pregunta')),
            ],
        ),
    ]
