# Generated by Django 5.1.2 on 2024-11-11 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0003_pregunta_alter_chat_renta_respuesta'),
        ('tools', '0007_categoria_tool_categoria'),
        ('users', '0006_arrendador_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendatario')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
            options={
                'unique_together': {('arrendatario', 'herramienta')},
            },
        ),
    ]
