# Generated by Django 4.2.16 on 2024-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0004_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
