# Generated by Django 5.1.2 on 2024-11-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0004_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
