# Generated by Django 5.1.2 on 2024-11-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0005_alter_resena_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
