# Generated by Django 5.1.2 on 2024-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0006_alter_resena_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
