# Generated by Django 5.1.2 on 2024-11-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0007_chat_oculto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='oculto',
            new_name='oculto_arrendador',
        ),
        migrations.AddField(
            model_name='chat',
            name='oculto_arrendatario',
            field=models.BooleanField(default=False),
        ),
    ]
