# Generated by Django 5.1.2 on 2024-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0008_rename_oculto_chat_oculto_arrendador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='chat_archivos/'),
        ),
    ]
