# Generated by Django 5.1.2 on 2024-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0009_mensaje_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
