# Generated by Django 5.1.2 on 2024-11-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0010_alter_mensaje_contenido'),
        ('users', '0009_direccion_colonia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Retirado', 'Retirado')], default='Pendiente', max_length=20)),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendador')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentas.renta')),
            ],
        ),
    ]
