# Generated by Django 4.2.16 on 2024-11-18 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_remove_tool_disponibilidad'),
        ('users', '0009_direccion_colonia'),
        ('rentas', '0010_alter_mensaje_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='es_soporte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='arrendador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.arrendador'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='arrendatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.arrendatario'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.tool'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='renta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentas.renta'),
        ),
    ]
