# Generated by Django 5.1.2 on 2024-11-18 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0011_pago'),
        ('users', '0009_direccion_colonia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='renta',
        ),
        migrations.AddField(
            model_name='pago',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='arrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='users.arrendador'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Procesado', 'Procesado')], default='Pendiente', max_length=20),
        ),
    ]
