# Generated by Django 4.2.16 on 2024-11-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0011_chat_es_soporte_alter_chat_arrendador_and_more'),
        ('rentas', '0012_remove_pago_renta_pago_retirado_and_more'),
    ]

    operations = [
    ]
