# Generated by Django 5.1.2 on 2024-10-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_arrendador_ine_image_arrendatario_ine_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=100)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='tools/')),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.arrendador')),
            ],
        ),
    ]
