# Generated by Django 4.2.16 on 2024-10-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_carrito_renta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renta',
        ),
    ]
