# Generated by Django 4.2.16 on 2024-10-31 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_delete_renta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='costo_hora',
        ),
    ]
