# Generated by Django 4.2.16 on 2024-10-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_tool_costo_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
