# Generated by Django 4.2.16 on 2024-11-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_tool_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Disponible', 'Disponible'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
