# Generated by Django 5.1.2 on 2024-11-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_categoria_tool_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='mensaje_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
