# Generated by Django 5.1.2 on 2024-11-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_tool_mensaje_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
